# Form implementation generated from reading ui file 'bancafe.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TINH = QtWidgets.QLabel(parent=self.centralwidget)
        self.TINH.setGeometry(QtCore.QRect(300, 10, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.TINH.setFont(font)
        self.TINH.setObjectName("TINH")
        self.THONGTINHKH = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.THONGTINHKH.setGeometry(QtCore.QRect(30, 80, 791, 181))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.THONGTINHKH.setFont(font)
        self.THONGTINHKH.setObjectName("THONGTINHKH")
        self.label = QtWidgets.QLabel(parent=self.THONGTINHKH)
        self.label.setGeometry(QtCore.QRect(50, 40, 111, 16))
        self.label.setObjectName("label")
        self.name = QtWidgets.QLineEdit(parent=self.THONGTINHKH)
        self.name.setGeometry(QtCore.QRect(220, 40, 321, 22))
        self.name.setObjectName("name")
        self.label_2 = QtWidgets.QLabel(parent=self.THONGTINHKH)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 55, 16))
        self.label_2.setObjectName("label_2")
        self.sex = QtWidgets.QComboBox(parent=self.THONGTINHKH)
        self.sex.setGeometry(QtCore.QRect(220, 80, 73, 22))
        self.sex.setObjectName("sex")
        self.sex.addItem("")
        self.sex.addItem("")
        self.label_3 = QtWidgets.QLabel(parent=self.THONGTINHKH)
        self.label_3.setGeometry(QtCore.QRect(50, 120, 71, 16))
        self.label_3.setObjectName("label_3")
        self.date = QtWidgets.QDateEdit(parent=self.THONGTINHKH)
        self.date.setGeometry(QtCore.QRect(220, 120, 110, 22))
        self.date.setObjectName("date")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 290, 781, 161))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.cafe_da = QtWidgets.QCheckBox(parent=self.groupBox)
        self.cafe_da.setGeometry(QtCore.QRect(60, 50, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cafe_da.setFont(font)
        self.cafe_da.setObjectName("cafe_da")
        self.cafe_sua = QtWidgets.QCheckBox(parent=self.groupBox)
        self.cafe_sua.setGeometry(QtCore.QRect(230, 50, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cafe_sua.setFont(font)
        self.cafe_sua.setObjectName("cafe_sua")
        self.nuoc_cam = QtWidgets.QCheckBox(parent=self.groupBox)
        self.nuoc_cam.setGeometry(QtCore.QRect(400, 50, 101, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nuoc_cam.setFont(font)
        self.nuoc_cam.setObjectName("nuoc_cam")
        self.nuoc_ngot = QtWidgets.QCheckBox(parent=self.groupBox)
        self.nuoc_ngot.setGeometry(QtCore.QRect(570, 50, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nuoc_ngot.setFont(font)
        self.nuoc_ngot.setObjectName("nuoc_ngot")
        self.sl_cfd = QtWidgets.QSpinBox(parent=self.groupBox)
        self.sl_cfd.setGeometry(QtCore.QRect(60, 90, 42, 22))
        self.sl_cfd.setObjectName("sl_cfd")
        self.sl_cfs = QtWidgets.QSpinBox(parent=self.groupBox)
        self.sl_cfs.setGeometry(QtCore.QRect(230, 90, 42, 22))
        self.sl_cfs.setObjectName("sl_cfs")
        self.sl_nc = QtWidgets.QSpinBox(parent=self.groupBox)
        self.sl_nc.setGeometry(QtCore.QRect(400, 90, 42, 22))
        self.sl_nc.setObjectName("sl_nc")
        self.nguoi_4 = QtWidgets.QSpinBox(parent=self.groupBox)
        self.nguoi_4.setGeometry(QtCore.QRect(570, 90, 42, 22))
        self.nguoi_4.setObjectName("nguoi_4")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 90, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(200, 90, 31, 16))
        self.label_5.setObjectName("label_5")
        self.sl_nn = QtWidgets.QLabel(parent=self.groupBox)
        self.sl_nn.setGeometry(QtCore.QRect(540, 90, 31, 16))
        self.sl_nn.setObjectName("sl_nn")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(370, 90, 31, 16))
        self.label_7.setObjectName("label_7")
        self.thanh_tien = QtWidgets.QPushButton(parent=self.centralwidget)
        self.thanh_tien.setGeometry(QtCore.QRect(250, 480, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.thanh_tien.setFont(font)
        self.thanh_tien.setObjectName("thanh_tien")
        self.thanhtien = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.thanhtien.setGeometry(QtCore.QRect(380, 480, 161, 22))
        self.thanhtien.setObjectName("thanhtien")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(560, 490, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.thanh_tien.clicked.connect(self.tinh_tien)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BÁN CAFE"))
        self.TINH.setText(_translate("MainWindow", "BÁN CAFE"))
        self.THONGTINHKH.setTitle(_translate("MainWindow", "THÔNG TIN KHÁCH HÀNG"))
        self.label.setText(_translate("MainWindow", "Tên Khách Hàng"))
        self.label_2.setText(_translate("MainWindow", "Giới Tính"))
        self.sex.setItemText(0, _translate("MainWindow", "Nam"))
        self.sex.setItemText(1, _translate("MainWindow", "Nữ"))
        self.label_3.setText(_translate("MainWindow", "Ngày Mua"))
        self.groupBox.setTitle(_translate("MainWindow", "Dịch Vụ"))
        self.cafe_da.setText(_translate("MainWindow", "CAFE ĐÁ"))
        self.cafe_sua.setText(_translate("MainWindow", "CAFE ĐEN"))
        self.nuoc_cam.setText(_translate("MainWindow", "NƯỚC CAM"))
        self.nuoc_ngot.setText(_translate("MainWindow", "NƯỚC NGỌT"))
        self.label_4.setText(_translate("MainWindow", "SL"))
        self.label_5.setText(_translate("MainWindow", "SL"))
        self.sl_nn.setText(_translate("MainWindow", "SL"))
        self.label_7.setText(_translate("MainWindow", "SL"))
        self.thanh_tien.setText(_translate("MainWindow", "Thành Tiền"))
        self.label_6.setText(_translate("MainWindow", "VND"))

    def tinh_tien(self):
        price = {
            "cafe_da":10000,
            "cafe_sua":20000,
            "nuoc_cam":15000,
            "nuoc_ngot":10000,
            "sl_cfd":10000,
            "sl_cfs":20000,
            "sl_nc":15000,
            "nguoi_4":10000
                }
        tcf=0
        if self.cafe_da.checkState()!=0:
            tcf=price["cafe_da"]
        tcfs=0
        if self.cafe_sua.checkState()!=0:
            tcfs=price["cafe_sua"]
        tnc=0
        if self.nuoc_cam.checkState()!=0:
            tnc=price["nuoc_cam"]
        tnn=0
        if self.nuoc_ngot.checkState()!=0:
            tnn=price["nuoc_ngot"]
        cfd=int(self.sl_cfd.text())*price["sl_cfd"]
        cfs=int(self.sl_cfs.text())*price["sl_cfs"]
        nc=int(self.sl_nc.text())*price["sl_nc"]
        nn=int(self.nguoi_4.text())*price["nguoi_4"]
        sum=cfd+cfs+nc+nn
        self.thanhtien.setText(str(sum))
        hoa_hon=QtWidgets.QMessageBox()
        hoa_hon.setInformativeText(f'Tiền Phải Trả là: {sum}')
        hoa_hon.exec()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
