# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore,QtGui,QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 543)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 40, 411, 111))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 190, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 270, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tai_khoan = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tai_khoan.setGeometry(QtCore.QRect(230, 190, 311, 22))
        self.tai_khoan.setObjectName("tai_khoan")
        self.mat_khau = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.mat_khau.setGeometry(QtCore.QRect(230, 270, 311, 22))
        self.mat_khau.setObjectName("mat_khau")
        self.dang_nhap = QtWidgets.QPushButton(parent=self.centralwidget)
        self.dang_nhap.setGeometry(QtCore.QRect(310, 340, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dang_nhap.setFont(font)
        self.dang_nhap.setStyleSheet("blackground:rgb(34, 170, 91)")
        self.dang_nhap.setObjectName("dang_nhap")
        self.tao_tk = QtWidgets.QPushButton(parent=self.centralwidget)
        self.tao_tk.setGeometry(QtCore.QRect(450, 430, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tao_tk.setFont(font)
        self.tao_tk.setStyleSheet("blackground:rgb(34, 170, 91)")
        self.tao_tk.setObjectName("tao_tk")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ĐĂNG NHẬP"))
        self.label_2.setText(_translate("MainWindow", "TÀI KHOẢN"))
        self.label_3.setText(_translate("MainWindow", "MẬT KHẨU"))
        self.tai_khoan.setText(_translate("MainWindow", "username"))
        self.mat_khau.setText(_translate("MainWindow", "passwork"))
        self.dang_nhap.setText(_translate("MainWindow", "ĐĂNG NHẬP"))
        self.tao_tk.setText(_translate("MainWindow", "TẠO TÀI KHOẢN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
