# Form implementation generated from reading ui file 'tao_tai_khoan.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 50, 501, 111))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 210, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 300, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tao_tk = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tao_tk.setGeometry(QtCore.QRect(280, 210, 311, 22))
        self.tao_tk.setObjectName("tao_tk")
        self.tao_mk = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tao_mk.setGeometry(QtCore.QRect(280, 310, 311, 22))
        self.tao_mk.setObjectName("tao_mk")
        self.tao_tai_khoan = QtWidgets.QPushButton(parent=self.centralwidget)
        self.tao_tai_khoan.setGeometry(QtCore.QRect(310, 370, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tao_tai_khoan.setFont(font)
        self.tao_tai_khoan.setStyleSheet("blackground:rgb(34, 170, 91)")
        self.tao_tai_khoan.setObjectName("tao_tai_khoan")
        self.quay_lai = QtWidgets.QPushButton(parent=self.centralwidget)
        self.quay_lai.setGeometry(QtCore.QRect(580, 460, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.quay_lai.setFont(font)
        self.quay_lai.setStyleSheet("blackground:rgb(34, 170, 91)")
        self.quay_lai.setObjectName("quay_lai")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TẠO TÀI KHOẢN"))
        self.label_2.setText(_translate("MainWindow", "TÀI KHOẢN"))
        self.label_3.setText(_translate("MainWindow", "MẬT KHẨU"))
        self.tao_tk.setText(_translate("MainWindow", "username"))
        self.tao_mk.setText(_translate("MainWindow", "passwork"))
        self.tao_tai_khoan.setText(_translate("MainWindow", "TẠO TÀI KHOẢN"))
        self.quay_lai.setText(_translate("MainWindow", "QUAY LẠI ĐĂNG NHẬP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
